-- Uso de ALTER TABLE 

-- A. ADC A TABELA A COLUNA EMAIL

ALTER TABLE paciente
ADD COLUMN email TEXT;

-- B AUMENTAR O LIMITE DE CARACTERES SUPORTADOS NA COLUNA ESPECIALIZAÇÃO DA TABELA MEDICO

ALTER TABLE medico
MODIFY COLUMN especializacao TYPE VARCHAR(50);